Jetsurf/jet-bot

bot.py

This might make the maps list pretty.

Prettier maps list

---

bot.py
discordbot.json.example

Added !restart and !servers listing for owners of the bot (discord ID's in discordbot.json)

Added owner only commands (Jetsurf+Andy)

---

bot.py
commandparser.py

I believe this is 100% working now.

Store per-server command prefix in DB.

---

bot.py
discordbot.json.example

Leverage Discord API to determine owner accounts for owner-only commands vs using ID's in json config

Use Discord API for owners

---

splatinfo.py

SplatInfo class

---

nsohandler.py
nsotoken.py
splatinfo.py

Encapsulate token table stuff within Nsotoken class.

---

bot.py
modules/commandparser.py
modules/mysqlhandler.py
modules/mysqlinfo.py
modules/nsohandler.py
modules/nsotoken.py
modules/serverconfig.py
modules/serverutils.py
modules/vserver.py

Massive change to mysql handling. Make use of aiomysql and connection pools.

Move to aiomysql pool/connection broker

---

bot.py
modules/nsohandler.py
modules/nsotoken.py
modules/splatinfo.py
modules/vserver.py
requirements.txt

StoreDM overhaul
Weapons List
Maps List
Bug Fixes

StoreDM, Weapons/Maps list

---

bot.py
modules/nsohandler.py
modules/nsotoken.py
modules/vserver.py

Fix some bugs with vserver
Better ordering in nsohandler
Actual error handling/logging in nsotoken

Bug Fixes to vserver/nsohandler/nsotoken

---

modules/nsohandler.py

Fixed bugs in store ordering failing and thinking errors happened when they didn't

Fix to store ordering + ordering in DM's

---

bot.py
modules/nsohandler.py

No longer throws exceptions when using !order with no ID

Minor Bug Fixes

---

bot.py
modules/nsohandler.py
modules/nsotoken.py

Added error handling + arg usage to storedm
Added timestamps for iksm updates and session token add times (finally)

storedm and iksm/session token date handling

---

modules/nsotoken.py

Login process changed again, fixes for it

Fixes for NSO 1.6.1.2 update

---

bot.py
modules/achandler.py
modules/nsohandler.py
modules/nsotoken.py

Incorporates AC Passport functionality.
Decouples !token command from generating IKSM tokens.
!!! Likely to introduce bugs with the partial NSOtoken handler rewrite. Tested in most use cases !!!

AC Passport functionality

---

README.md
bot.py
help/usersplatnet.txt
modules/nsohandler.py
modules/splatinfo.py

Use Partial (and whole) item names to order from the NSO store.

Rework !order to use partial terms

---

modules/nsotoken.py

NSO App version updated to 1.8.0 - No breaking changes seen so far

NSO Version Bump

---

bot.py
modules/nsotoken.py
modules/serverutils.py

Removed all dependency on active admins list for admin perms.
Added proper member list intent

Remove active admin list, add proper guild member intents

---

README.md
bot.py
help/admin.txt
modules/nsohandler.py
modules/nsotoken.py
modules/serverutils.py
modules/vserver.py
requirements.txt

Implemented feeds for updates on notifications, configurable with sections.
- Can include maps/gamemodes, Salmon Run, and the new gear on the store
Check !help admin or the README on how to set this up

Notification Feeds Implemented

---

bot.py
config/discordbot.json.example
modules/nsohandler.py

There are issues present with caching member lists causing problems with storedms and admin/owner permissions.

Fixes for perm/storedm issues

---

modules/nsohandler.py

This should fix time remaining calculations on servers that aren't configured to use UTC for their local time.

fixed server timezone handling for remaining time

---

modules/nsohandler.py

Authored-by: hartie95 <mail@hartie95.de>

fixed timezone handling for remaining time (#133)

---

modules/nsohandler.py
modules/splatinfo.py

Untested but pretty trivial. :-)

Add 'weapon info' help text and a couple of weapon aliases.

---

modules/nsohandler.py
modules/nsotoken.py
modules/splatinfo.py

For Issue
https://github.com/Jetsurf/jet-bot/issues/118

Debug info/error handling

---

modules/vserver.py

Andy made most of this PR, I adapted work from him to merge into the bot

Fix for youtube video searching

---

bot.py
modules/serverutils.py
modules/vserver.py

Prep for a bulk cleanup of stale DB entries from servers the bot has left.

Add MySQL deletion on guild leave.

---

modules/nsohandler.py

Attempt to track down key errors in retrieving json from NSO

Add error checks to map/weapon json

---

modules/nsohandler.py
modules/nsotoken.py

Fix for situation when someone DM's the bot with !token and completes the process again, allows for multiple token entries.

Fix Duplicate Tokens being added

---

bot.py
modules/nsohandler.py
modules/nsotoken.py
modules/vserver.py

Large chunks of code converted to formatted strings
Added weapon badges to weapon stats cmd
Numerous bug fixes

Readability + Weapon Badges + Bug Fixes

---

bot.py
config/discordbot.json.example
modules/commandparser.py
modules/nsotoken.py

This will be the last (minus any small issues) commit where discord.py will be the library used. Py-cord will be leveraged from this point forward.

Last discord.py commit

---

bot.py
modules/nsohandler.py
modules/nsotoken.py

Will properly respond if there is no response from you

HOTFIX: Fix for storedm issues

---

modules/nsohandler.py
modules/nsotoken.py

HOTFIX: NSO Commands not working

---

README.md
bot.py
help/admin-slash.txt
help/basesplatnet-slash.txt
help/botinfo-slash.txt
help/music-slash.txt
help/usersplatnet-slash.txt
modules/nsohandler.py
modules/serverutils.py
modules/vserver.py

Adds a new /help view to explain commands from within the bot (rather than going to the README)
General house keeping to stay current with pycord.

Add Help Menu

---

modules/nsotoken.py

Fixes acnh passports not working - Nintendo update their API header

Fix for Token Generation/ACNH Passports

---

bot.py

Latest pycord versions made breaking changes to permissions.
Using this version as a self hosted bot will silently error when someone other than the owner runs these commands.

Fix for latest pycord release

---

bot.py
modules/achandler.py
modules/mysqlschema.py
modules/nsohandler.py
modules/nsotoken.py

Needed to include tokens migration
Also proper error checking for tokens on nso calls.

HOTFIX: Migrate tokens

---

bot.py
modules/gameinfo/matchset.py
modules/gameinfo/splat3.py
modules/s3handler.py

Merge preliminary S3 stuff from dev

Splatoon 3 Initial Commands

---

.gitignore
README.md
bot.py
data/splat3.json
help/splatoon3-slash.txt
modules/gameinfo/matchset.py
modules/gameinfo/splat3.py
modules/s3/imagebuilder.py
modules/s3/schedule.py
modules/s3/storedm.py
modules/s3handler.py

In preparation for S3 Chill Season.

Merge dev to master

---

modules/nsotoken.py
modules/youtube.py

Add NXApi override, include /token links to f-providers and improved language
Youtube search fixes.

NXApi Override + YT Search Fix

---

bot.py
config/discordbot.json.example
modules/nsotoken.py
modules/stringcrypt.py
modules/vserver.py
modules/youtube.py
requirements.txt

Youtube-dl has been throwing 403's for a long while. This merge is moving to yt-dlp to get functional playback working again.
Requires a custom ffmpeg binary to work with yt-dlp correctly. Use the new config option 'ffmpeg_bin' to point to the ffmpeg binary provided by https://github.com/yt-dlp/FFmpeg-Builds

Move from youtube-dl to yt-dlp
